import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import AcademicPartners from "@/components/AcademicPartners";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex flex-col lg:flex-row items-start min-h-screen">
          <SideBar />
          <main className="flex-grow">{children}</main>
          <AcademicPartners />
        </div>
      </body>
    </html>
  );
}
